direccion_index:
    path:     /
    defaults: { _controller: "UserBundle:Address:index" }
    methods:  GET

direccion_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:Address:show" }
    methods:  GET

direccion_new:
    path:     /new
    defaults: { _controller: "UserBundle:Address:new" }
    methods:  [GET, POST]

direccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Address:edit" }
    methods:  [GET, POST]

direccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Address:delete" }
    methods:  DELETE
