personas_index:
    path:     /
    defaults: { _controller: "UserBundle:People:index" }
    methods:  GET

personas_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:People:show" }
    methods:  GET

personas_new:
    path:     /new
    defaults: { _controller: "UserBundle:People:new" }
    methods:  [GET, POST]

personas_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:People:edit" }
    methods:  [GET, POST]

personas_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:People:delete" }
    methods:  DELETE
